version: 1.0.0.0.{build}

branches:
  only:
  - master
skip_tags: false

os: Visual Studio 2015
configuration: Release

clone_depth: 1
clone_folder: C:\_Repos\DWS

build:
  parallel: true
  project: DWS.sln
  verbosity: detailed

after_build:
- cmd: msbuild DWS.sln
- cmd: md DWS-Build
- cmd: copy DWS\bin\Release\DWS.exe DWS-Build
- cmd: 7z a -tzip "DWS-build.zip" DWS-Build/*.*

artifacts:
- path: DWS-build.zip
