version: 5.{build}

os: Visual Studio 2019
configuration: Release

clone_depth: 1
clone_folder: C:\_Repos\DWS

build:
  parallel: true
  project: DWS.sln
  verbosity: minimal

after_build:
- cmd: md DWS-Build
- cmd: copy DWS\bin\Release\DWS.exe DWS-Build
- cmd: 7z a -tzip "DWS-build.zip" DWS-Build/*.*

artifacts:
- path: DWS-build.zip
  name: Binaries
